-- 코드를 입력하세요
SELECT MCDP_CD , COUNT(MCDP_CD)
FROM APPOINTMENT 
 # WHERE DATE_FORMAT(APNT_YMD,'%Y-%m') = '2022-05'
 WHERE APNT_YMD LIKE '2022-05%'
group by MCDP_CD
order by COUNT(MCDP_CD) ASC , MCDP_CD ASC
